# Generated by Django 2.1.3 on 2019-04-02 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('google_address', '0006_delete_googleregion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressComponentLocalized',
            fields=[
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                                   related_name='i18n', serialize=False,
                                                   to='google_address.AddressComponent')),
                ('short_name_ru', models.CharField(blank=True, default='', max_length=400)),
                ('short_name_uk', models.CharField(blank=True, default='', max_length=400)),
                ('long_name_ru', models.CharField(blank=True, default='', max_length=400)),
                ('long_name_uk', models.CharField(blank=True, default='', max_length=400)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
